// ═══════════════════════════════════════════
// Nurture Paradise — Plant Database  
// js/plants.js — India-centric plants with city-climate matching
// ═══════════════════════════════════════════

// ── CLIMATE ZONES ───────────────────────────────────────────────────────────
// tropical          : Hot & humid year-round. Rain > 1500mm. Kerala, coastal AP, Goa, Andaman
// subtropical       : Hot summers, mild winters. UP plains, Bihar, peninsular plateau, Punjab
// semiarid          : Hot & dry, 400-700mm rain. Parts of Rajasthan, Telangana, interior Maharashtra
// arid              : Very hot, very dry, <400mm rain. Rajasthan desert, Kutch
// highland          : Cool to cold, high altitude. Himachal, Uttarakhand, NE hills, Nilgiris, Coorg
// humid_subtropical : Hot humid summers, cool winters. Bengal, Assam, Odisha, NE plains

// ── INDIA CITY → CLIMATE MAP ─────────────────────────────────────────────────
const CITY_CLIMATE_MAP = [
  // North India
  { keys: ['delhi','new delhi'], zone: 'subtropical', label: 'Delhi', temp: '7–44°C', rain: 'Low (750mm)', season: 'Oct–Feb best sowing' },
  { keys: ['noida','ghaziabad','faridabad','gurugram','gurgaon'], zone: 'subtropical', label: 'NCR', temp: '7–44°C', rain: 'Low (750mm)', season: 'Oct–Feb best sowing' },
  { keys: ['agra'], zone: 'subtropical', label: 'Agra', temp: '6–45°C', rain: 'Low (700mm)', season: 'Oct–Feb best sowing' },
  { keys: ['lucknow','kanpur','allahabad','prayagraj','varanasi','gorakhpur'], zone: 'subtropical', label: 'UP Plains', temp: '6–46°C', rain: 'Moderate (850mm)', season: 'Oct–Mar best sowing' },
  { keys: ['jaipur','jodhpur','kota','ajmer','bikaner'], zone: 'semiarid', label: 'Rajasthan', temp: '5–45°C', rain: 'Low (500mm)', season: 'Oct–Mar and post-monsoon' },
  { keys: ['jaisalmer','barmer','churu'], zone: 'arid', label: 'Thar Desert', temp: '2–48°C', rain: 'Very low (<300mm)', season: 'Nov–Feb only' },
  { keys: ['udaipur','mount abu'], zone: 'semiarid', label: 'South Rajasthan', temp: '8–40°C', rain: 'Low–moderate', season: 'Oct–Mar' },
  { keys: ['chandigarh','ludhiana','amritsar','jalandhar','patiala'], zone: 'subtropical', label: 'Punjab', temp: '4–44°C', rain: 'Moderate (700mm)', season: 'Oct–Mar best sowing' },
  { keys: ['shimla','manali','dharamshala','solan','mandi'], zone: 'highland', label: 'Himachal Pradesh', temp: '-5–30°C', rain: 'Moderate–high', season: 'Mar–Jun and Sep–Oct' },
  { keys: ['dehradun','haridwar','rishikesh','mussoorie'], zone: 'highland', label: 'Uttarakhand foothills', temp: '5–38°C', rain: 'High (2000mm)', season: 'Mar–Jun and Sep–Oct' },
  { keys: ['nainital','almora','ranikhet'], zone: 'highland', label: 'Kumaon Hills', temp: '2–32°C', rain: 'High', season: 'Apr–Jun and Sep–Oct' },
  // East & Northeast India
  { keys: ['kolkata','calcutta','howrah','durgapur','asansol'], zone: 'humid_subtropical', label: 'West Bengal', temp: '12–40°C', rain: 'High (1600mm)', season: 'Oct–Mar best sowing' },
  { keys: ['bhubaneswar','cuttack','puri','rourkela'], zone: 'humid_subtropical', label: 'Odisha', temp: '13–42°C', rain: 'High (1500mm)', season: 'Oct–Mar' },
  { keys: ['patna','gaya','bhagalpur','muzaffarpur'], zone: 'humid_subtropical', label: 'Bihar', temp: '8–44°C', rain: 'Moderate (1100mm)', season: 'Oct–Mar' },
  { keys: ['ranchi','jamshedpur','dhanbad'], zone: 'humid_subtropical', label: 'Jharkhand', temp: '10–42°C', rain: 'Moderate–high', season: 'Oct–Mar' },
  { keys: ['guwahati','dibrugarh','silchar','jorhat'], zone: 'humid_subtropical', label: 'Assam', temp: '8–35°C', rain: 'Very high (1700mm)', season: 'Year-round mostly' },
  { keys: ['shillong','aizawl','agartala','imphal','kohima','itanagar'], zone: 'highland', label: 'NE Hills', temp: '5–30°C', rain: 'Very high', season: 'Mar–Jun and Sep–Nov' },
  // Central India
  { keys: ['bhopal','indore','gwalior','jabalpur','ujjain','rewa'], zone: 'subtropical', label: 'Madhya Pradesh', temp: '5–44°C', rain: 'Moderate (1000mm)', season: 'Oct–Mar best sowing' },
  { keys: ['nagpur','amravati','akola','yavatmal'], zone: 'semiarid', label: 'Vidarbha', temp: '8–47°C', rain: 'Moderate (900mm)', season: 'Oct–Mar' },
  { keys: ['raipur','bilaspur','durg','bhilai'], zone: 'subtropical', label: 'Chhattisgarh', temp: '10–44°C', rain: 'High (1200mm)', season: 'Oct–Mar' },
  // West India
  { keys: ['mumbai','thane','navi mumbai','pune','nashik','aurangabad','solapur'], zone: 'tropical', label: 'Maharashtra', temp: '16–38°C', rain: 'High coastal, mod interior', season: 'Oct–Mar and Jul–Sep' },
  { keys: ['kolhapur','sangli','satara'], zone: 'subtropical', label: 'South Maharashtra', temp: '14–38°C', rain: 'Moderate–high', season: 'Oct–Mar' },
  { keys: ['ahmedabad','surat','vadodara','rajkot','gandhinagar'], zone: 'semiarid', label: 'Gujarat', temp: '10–43°C', rain: 'Moderate (750mm)', season: 'Oct–Mar' },
  { keys: ['bhuj','kutch','bhavnagar'], zone: 'arid', label: 'Kutch', temp: '7–45°C', rain: 'Very low (<400mm)', season: 'Nov–Feb' },
  { keys: ['panaji','goa','margao','vasco'], zone: 'tropical', label: 'Goa', temp: '20–35°C', rain: 'Very high (2900mm)', season: 'Oct–Apr, avoid peak monsoon' },
  // South India
  { keys: ['bengaluru','bangalore','mysuru','mysore','hubli','dharwad','belagavi'], zone: 'subtropical', label: 'Karnataka plateau', temp: '15–35°C', rain: 'Moderate (900mm)', season: 'Sep–Feb best sowing' },
  { keys: ['mangaluru','mangalore','udupi'], zone: 'tropical', label: 'Coastal Karnataka', temp: '20–35°C', rain: 'Very high (3500mm)', season: 'Oct–May' },
  { keys: ['hyderabad','secunderabad','warangal','nizamabad','karimnagar'], zone: 'semiarid', label: 'Telangana', temp: '13–43°C', rain: 'Moderate (800mm)', season: 'Oct–Mar' },
  { keys: ['visakhapatnam','vizag','vijayawada','guntur','tirupati','nellore','kurnool'], zone: 'tropical', label: 'Andhra Pradesh', temp: '18–42°C', rain: 'High (1000mm)', season: 'Oct–Mar' },
  { keys: ['chennai','coimbatore','madurai','trichy','tiruchirappalli','salem','tirunelveli','vellore'], zone: 'tropical', label: 'Tamil Nadu', temp: '20–40°C', rain: 'High (1200mm)', season: 'Oct–Feb' },
  { keys: ['thiruvananthapuram','trivandrum','kochi','cochin','kozhikode','calicut','thrissur','palakkad','kollam'], zone: 'tropical', label: 'Kerala', temp: '22–35°C', rain: 'Extremely high (3000mm)', season: 'Oct–May, year-round possible' },
  { keys: ['pondicherry','puducherry'], zone: 'tropical', label: 'Pondicherry', temp: '20–38°C', rain: 'High (1200mm)', season: 'Oct–Mar' },
  { keys: ['ooty','udhagamandalam','kodaikanal','coorg','munnar','wayanad'], zone: 'highland', label: 'South Indian Hills', temp: '8–28°C', rain: 'High', season: 'Year-round, avoid Dec–Jan peak cold' },
];

// ── RESOLVE CITY → CLIMATE ENTRY ─────────────────────────────────────────────
function resolveCityClimate(cityInput) {
  if (!cityInput) return null;
  const q = cityInput.trim().toLowerCase();
  for (const entry of CITY_CLIMATE_MAP) {
    if (entry.keys.some(k => q.includes(k) || k.includes(q))) return entry;
  }
  return null;
}

// ── SUITABILITY SCORE ─────────────────────────────────────────────────────────
// Returns 3 (Best), 2 (Good), 1 (Possible), 0 (Not recommended)
function getPlantSuitability(plant, zone) {
  if (!zone || !plant.climate) return 2;
  if (plant.climate.best && plant.climate.best.includes(zone)) return 3;
  if (plant.climate.good && plant.climate.good.includes(zone)) return 2;
  if (plant.climate.possible && plant.climate.possible.includes(zone)) return 1;
  return 0;
}

const SUITABILITY_LABEL = {
  3: '⭐ Best for your city',
  2: '✓ Grows well here',
  1: '⚠ Possible with care',
  0: '✗ Not recommended'
};
const SUITABILITY_CLASS = {
  3: 'suit-best',
  2: 'suit-good',
  1: 'suit-possible',
  0: 'suit-none'
};

const PLANT_DB = [
// ──────── 🪴 INDOOR ────────
{id:101,common:"Monstera",latin:"Monstera deliciosa",img:"https://in.pinterest.com/pin/70437490118440/",water:"Weekly",sun:"Bright indirect",cycle:"Perennial",cats:["indoor"],diff:"Easy",height:"Up to 3m",soil:"Well-draining with perlite",ph:"5.5-7.0",fertilizer:"Monthly in season",propagation:"Stem cuttings in water",pests:"Spider mites, scale",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Rare indoors"},companion:["Pothos","Peace Lily"],tips:["Wipe leaves monthly","Mist in AC rooms","Yellow leaves = overwatering","Toxic to pets","Support with moss pole"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:102,common:"Money Plant (Pothos)",latin:"Epipremnum aureum",img:"https://i.pinimg.com/736x/d7/71/b6/d771b669f81b1e856676af7ffbe41c51.jpg",water:"Every 1-2 weeks",sun:"Low to bright indirect",cycle:"Perennial",cats:["indoor","outdoor"],diff:"Easy",height:"Trailing 10m",soil:"Any well-draining",ph:"6.1-6.8",fertilizer:"Monthly",propagation:"Cuttings in water",pests:"Mealybugs, root rot",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Rarely"},companion:["Snake Plant","ZZ Plant"],tips:["Nearly impossible to kill","Grows in water or soil","Trim to keep bushy","Toxic to pets","Removes formaldehyde"],climate:{best:["tropical","humid_subtropical","subtropical"],good:["semiarid","arid","highland"],possible:[]}},
{id:103,common:"Peace Lily",latin:"Spathiphyllum wallisii",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Spathiphyllum_cochlearispathum_RTBG.jpg/400px-Spathiphyllum_cochlearispathum_RTBG.jpg",water:"Weekly",sun:"Low to medium indirect",cycle:"Perennial",cats:["indoor","flowering"],diff:"Easy",height:"30-90cm",soil:"Rich well-draining",ph:"5.8-6.5",fertilizer:"Every 6 weeks",propagation:"Division at roots",pests:"Spider mites, mealybugs",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Spring and autumn"},companion:["Pothos","Ferns"],tips:["Droops when thirsty — good indicator","Keep from AC vents","Toxic to pets","NASA air purifier","White flowers = healthy care"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","arid","highland"]}},
{id:104,common:"Snake Plant",latin:"Dracaena trifasciata",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Sansevieria_trifasciata_var_laurentii.jpg/400px-Sansevieria_trifasciata_var_laurentii.jpg",water:"Every 2-6 weeks",sun:"Any light",cycle:"Perennial",cats:["indoor"],diff:"Easy",height:"60cm-1.5m",soil:"Sandy cactus mix",ph:"5.5-7.5",fertilizer:"Twice a year",propagation:"Leaf cuttings or division",pests:"Root rot from overwatering",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Rare fragrant white"},companion:["ZZ Plant","Pothos"],tips:["Most forgiving houseplant","Releases oxygen at night","Perfect for Indian apartments","Removes benzene","Toxic to pets"],climate:{best:["tropical","subtropical","semiarid","arid","humid_subtropical"],good:["highland"],possible:[]}},
{id:105,common:"Spider Plant",latin:"Chlorophytum comosum",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Chlorophytum_comosum_0zz.jpg/400px-Chlorophytum_comosum_0zz.jpg",water:"Weekly",sun:"Indirect light",cycle:"Perennial",cats:["indoor"],diff:"Easy",height:"30-60cm",soil:"Well-draining mix",ph:"6.0-7.2",fertilizer:"Monthly in season",propagation:"Plantlets from runners",pests:"Aphids, spider mites",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Small white on runners"},companion:["Peace Lily","Pothos"],tips:["Produces baby plantlets","Safe for pets and children","Brown tips = fluoride water","Good for hanging baskets","Very popular in India"],climate:{best:["tropical","humid_subtropical","subtropical"],good:["semiarid"],possible:["arid","highland"]}},
{id:106,common:"ZZ Plant",latin:"Zamioculcas zamiifolia",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Zamioculcas_zamiifolia.jpg/400px-Zamioculcas_zamiifolia.jpg",water:"Every 2-3 weeks",sun:"Low to medium indirect",cycle:"Perennial",cats:["indoor"],diff:"Easy",height:"60-90cm",soil:"Well-draining with sand",ph:"6.0-7.0",fertilizer:"Spring and summer",propagation:"Leaf cuttings or division",pests:"Scale, mealybugs",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Rare"},companion:["Snake Plant","Pothos"],tips:["Survives severe neglect","Glossy leaves naturally shine","Overwatering is only threat","Toxic to pets","Perfect office plant"],climate:{best:["tropical","subtropical","semiarid","arid","humid_subtropical"],good:["highland"],possible:[]}},
{id:107,common:"Fiddle Leaf Fig",latin:"Ficus lyrata",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Ficus_lyrata_2.jpg/400px-Ficus_lyrata_2.jpg",water:"Weekly",sun:"Bright indirect — consistent",cycle:"Perennial",cats:["indoor"],diff:"Moderate",height:"Up to 3m",soil:"Well-draining slightly acidic",ph:"6.0-7.0",fertilizer:"Monthly spring-summer",propagation:"Stem cuttings",pests:"Root rot, spider mites",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Does not bloom indoors"},companion:["Pothos","Snake Plant"],tips:["Hates being moved","Wipe leaves monthly","Brown edges = low humidity","Away from AC","Popular in Indian interior design"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:108,common:"Rubber Plant",latin:"Ficus elastica",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Ficus_elastica_1.jpg/400px-Ficus_elastica_1.jpg",water:"Every 1-2 weeks",sun:"Bright indirect",cycle:"Perennial",cats:["indoor"],diff:"Easy",height:"Up to 3m",soil:"Well-draining mix",ph:"5.5-7.0",fertilizer:"Monthly in season",propagation:"Stem cuttings or air layering",pests:"Spider mites, mealybugs",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Does not bloom"},companion:["Monstera","Philodendron"],tips:["Dramatic statement plant","Burgundy variety popular in India","Clean with damp cloth","Milky sap irritates skin","Adapts well to Indian conditions"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:109,common:"Areca Palm",latin:"Dypsis lutescens",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Dypsis_lutescens1.jpg/400px-Dypsis_lutescens1.jpg",water:"Twice weekly summer",sun:"Bright indirect",cycle:"Perennial",cats:["indoor","tropical"],diff:"Easy",height:"1.5-3m",soil:"Well-draining palm mix",ph:"6.0-7.0",fertilizer:"Monthly palm fertilizer",propagation:"Division of clumps",pests:"Spider mites, scale",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Small yellow on mature plants"},companion:["Peace Lily","Philodendron"],tips:["Best natural humidifier","NASA top air purifier","Mist in dry summers","Yellow fronds = overwatering","Popular in Indian homes and offices"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:110,common:"Philodendron",latin:"Philodendron hederaceum",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Philodendron_hederaceum_var._oxycardium_02.jpg/400px-Philodendron_hederaceum_var._oxycardium_02.jpg",water:"Every 1-2 weeks",sun:"Medium to bright indirect",cycle:"Perennial",cats:["indoor"],diff:"Easy",height:"Trailing 1.2m",soil:"Rich well-draining",ph:"5.0-6.0",fertilizer:"Monthly spring-summer",propagation:"Stem cuttings in water",pests:"Mealybugs, aphids",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Rare"},companion:["Pothos","Monstera"],tips:["Fast growing and rewarding","Train on moss pole","Yellow = overwatering","Toxic to pets","Heartleaf most popular in India"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:111,common:"Calathea (Prayer Plant)",latin:"Calathea orbifolia",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Calathea_orbifolia1.jpg/400px-Calathea_orbifolia1.jpg",water:"Every 1-2 weeks filtered",sun:"Medium to low indirect",cycle:"Perennial",cats:["indoor"],diff:"Moderate",height:"30-60cm",soil:"Rich moisture-retaining",ph:"6.5",fertilizer:"Monthly diluted",propagation:"Division",pests:"Spider mites, browning tips",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Insignificant"},companion:["Ferns","Peace Lily"],tips:["Leaves fold at night like prayer","Use filtered water","Loves humidity","Brown tips = tap water fluoride","Beautiful patterned leaves"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:112,common:"Dracaena",latin:"Dracaena marginata",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Dracaena_marginata_MS_2268.jpg/400px-Dracaena_marginata_MS_2268.jpg",water:"Every 1-2 weeks",sun:"Indirect — tolerates low",cycle:"Perennial",cats:["indoor"],diff:"Easy",height:"1-2m",soil:"Well-draining mix",ph:"6.0-6.5",fertilizer:"Every 2 months",propagation:"Stem cuttings",pests:"Scale, mealybugs",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Fragrant white rarely"},companion:["Snake Plant","ZZ Plant"],tips:["NASA top air purifier","Tolerates low light","Yellow tips = fluoride","Toxic to pets","Red-edged variety popular"],climate:{best:["tropical","subtropical","humid_subtropical"],good:["semiarid"],possible:["arid","highland"]}},
{id:113,common:"Chinese Evergreen",latin:"Aglaonema commutatum",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Aglaonema_commutatum.JPG/400px-Aglaonema_commutatum.JPG",water:"Every 1-2 weeks",sun:"Low to medium indirect",cycle:"Perennial",cats:["indoor"],diff:"Easy",height:"30-90cm",soil:"Well-draining moist mix",ph:"6.0-6.5",fertilizer:"Monthly spring-summer",propagation:"Division or cuttings",pests:"Mealybugs, scale",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Occasional white"},companion:["Peace Lily","Dracaena"],tips:["Perfect for dim Indian offices","Many colourful varieties","More colour = more light","Toxic to pets","Very forgiving"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:114,common:"Lucky Bamboo",latin:"Dracaena sanderiana",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Lucky_bamboo.jpg/400px-Lucky_bamboo.jpg",water:"Change water every 7-10 days",sun:"Indirect light",cycle:"Perennial",cats:["indoor"],diff:"Easy",height:"60-90cm",soil:"Pebbles and water",ph:"6.0-6.5",fertilizer:"Few drops monthly",propagation:"Stem cuttings in water",pests:"Root rot if water stagnates",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Rarely"},companion:["Peace Lily","Jade Plant"],tips:["3=happiness 5=wealth 7=health","Keep from direct sun","Change water weekly","Most popular gift plant in India","Feng Shui prosperity symbol"],climate:{best:["tropical","subtropical","humid_subtropical","semiarid","arid","highland"],good:[],possible:[]}},
{id:115,common:"Jade Plant",latin:"Crassula ovata",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Crassula_ovata1.jpg/400px-Crassula_ovata1.jpg",water:"Every 2-3 weeks",sun:"Full sun to bright indirect",cycle:"Perennial",cats:["indoor","succulent"],diff:"Easy",height:"60cm-1.5m",soil:"Well-draining succulent mix",ph:"6.0-7.0",fertilizer:"Spring and summer only",propagation:"Leaf or stem cuttings",pests:"Mealybugs, overwatering",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Pink-white flowers winter"},companion:["Aloe Vera","Echeveria"],tips:["Symbol of luck and prosperity","Lives for decades","Water less in winter","Pink flowers when root-bound","Most gifted plant in India"],climate:{best:["semiarid","arid","subtropical"],good:["tropical","humid_subtropical"],possible:["highland"]}},
{id:116,common:"Syngonium",latin:"Syngonium podophyllum",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Syngonium_podophyllum_2.jpg/400px-Syngonium_podophyllum_2.jpg",water:"Every 1-2 weeks",sun:"Low to medium indirect",cycle:"Perennial",cats:["indoor"],diff:"Easy",height:"30-60cm",soil:"Well-draining mix",ph:"5.5-6.5",fertilizer:"Monthly in season",propagation:"Stem cuttings",pests:"Spider mites, aphids",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Rare"},companion:["Pothos","Philodendron"],tips:["Perfect for small apartments","Pink green white varieties","Compact then trails","Toxic to pets","Fast and easy growing"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:117,common:"Peperomia",latin:"Peperomia obtusifolia",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Peperomia_obtusifolia.JPG/400px-Peperomia_obtusifolia.JPG",water:"Every 2 weeks",sun:"Medium indirect",cycle:"Perennial",cats:["indoor"],diff:"Easy",height:"10-30cm",soil:"Well-draining airy mix",ph:"6.0-7.0",fertilizer:"Monthly diluted",propagation:"Leaf or stem cuttings",pests:"Root rot, mealybugs",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Tiny spike flowers"},companion:["Pothos","Haworthia"],tips:["Perfect for desks","Semi-succulent tolerates dry","Hundreds of varieties","Non-toxic — safe for pets","Most underrated plant"],climate:{best:["tropical","humid_subtropical","subtropical"],good:["semiarid"],possible:["arid","highland"]}},
{id:118,common:"Tradescantia",latin:"Tradescantia zebrina",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Tradescantia_zebrina.jpg/400px-Tradescantia_zebrina.jpg",water:"Every 1-2 weeks",sun:"Bright indirect",cycle:"Perennial",cats:["indoor"],diff:"Easy",height:"Trailing 30-60cm",soil:"Well-draining mix",ph:"5.0-6.0",fertilizer:"Monthly",propagation:"Cuttings root in one week",pests:"Spider mites",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Small pink-purple"},companion:["Pothos","Spider Plant"],tips:["Purple silver striped leaves","Great for hanging baskets","Propagates easily","Prune for colour","Bright indirect only"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:119,common:"Hoya (Wax Plant)",latin:"Hoya carnosa",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Hoya_carnosa.jpg/400px-Hoya_carnosa.jpg",water:"Every 2 weeks",sun:"Bright indirect",cycle:"Perennial",cats:["indoor","flowering"],diff:"Easy",height:"Trailing 4m",soil:"Well-draining bark mix",ph:"6.0-7.0",fertilizer:"Monthly in season",propagation:"Stem cuttings",pests:"Mealybugs, root rot",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Fragrant waxy star clusters"},companion:["Pothos","Syngonium"],tips:["Sweetly fragrant waxy flowers","Thrives on neglect","Never repot often — blooms root-bound","Leaves last years","Can be passed through generations"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:120,common:"String of Hearts",latin:"Ceropegia woodii",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Ceropegia_woodii.jpg/400px-Ceropegia_woodii.jpg",water:"Every 2 weeks",sun:"Bright indirect",cycle:"Perennial",cats:["indoor","succulent"],diff:"Easy",height:"Trailing 60-90cm",soil:"Well-draining succulent mix",ph:"6.0-7.5",fertilizer:"Monthly in season",propagation:"Cuttings in water or soil",pests:"Mealybugs, root rot",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Small tubular pink-purple"},companion:["String of Pearls","Hoya"],tips:["Heart-shaped silver-marked leaves","Grows from small tubers","Let soil dry completely","Perfect for shelf displays","Charming trailing plant"],climate:{best:["subtropical","semiarid"],good:["tropical","humid_subtropical"],possible:["arid","highland"]}},
{id:121,common:"Boston Fern",latin:"Nephrolepis exaltata",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Nephrolepis_exaltata.jpg/400px-Nephrolepis_exaltata.jpg",water:"Twice weekly — mist daily",sun:"Indirect filtered",cycle:"Perennial",cats:["indoor"],diff:"Moderate",height:"30-90cm",soil:"Rich moisture-retaining",ph:"5.0-5.5",fertilizer:"Monthly diluted",propagation:"Division",pests:"Scale, mealybugs",season:{best:"Year-round — loves monsoon",sow:"N/A",harvest:"N/A",bloom:"Ferns do not flower"},companion:["Calathea","Peace Lily"],tips:["Top air purifier","Loves Indian monsoon humidity","Mist daily in dry season","Great for shaded balconies","Yellow fronds = too much sun"]},
// ──────── 🌵 SUCCULENTS ────────
{id:201,common:"Aloe Vera",latin:"Aloe barbadensis miller",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Aloe_vera_flower_inset.png/400px-Aloe_vera_flower_inset.png",water:"Every 3 weeks",sun:"Full sun to bright indirect",cycle:"Perennial",cats:["indoor","succulent","medicinal"],diff:"Easy",height:"60-90cm",soil:"Sandy succulent mix",ph:"7.0-8.5",fertilizer:"Once in spring",propagation:"Pups at base",pests:"Root rot, mealybugs",season:{best:"Year-round",sow:"N/A",harvest:"Leaves year-round",bloom:"Orange spike summer"},companion:["Snake Plant","Jade Plant"],tips:["Gel soothes burns and skin","Most important medicinal plant","Terracotta pots for drainage","Yellow = overwatering","Popular on Indian balconies"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:202,common:"Echeveria",latin:"Echeveria elegans",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Echeveria_elegans_2.jpg/400px-Echeveria_elegans_2.jpg",water:"Every 2 weeks — soak and dry",sun:"Full sun",cycle:"Perennial",cats:["succulent"],diff:"Easy",height:"10-20cm",soil:"Coarse sandy mix",ph:"6.0",fertilizer:"Once in growing season",propagation:"Leaf cuttings or offsets",pests:"Mealybugs, root rot",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Pink-orange bell flowers"},companion:["Haworthia","Sedum"],tips:["Water at base only","More sun = more colour","Let dry completely between waterings","Great for terrariums","Perfect for balcony containers"],climate:{best:["semiarid","arid","subtropical"],good:["tropical"],possible:["humid_subtropical","highland"]}},
{id:203,common:"Haworthia",latin:"Haworthia fasciata",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Haworthia_fasciata.jpg/400px-Haworthia_fasciata.jpg",water:"Every 2-3 weeks",sun:"Indirect — shade tolerant",cycle:"Perennial",cats:["indoor","succulent"],diff:"Easy",height:"5-15cm",soil:"Sandy well-draining",ph:"6.0-7.0",fertilizer:"Once in spring",propagation:"Offsets at base",pests:"Root rot, scale",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"White tubular on long stems"},companion:["Echeveria","Jade Plant"],tips:["Ideal for low-light apartments","Compact for desks","Transparent windows channel light","Easy propagation","Hardy for India"],climate:{best:["semiarid","arid","subtropical"],good:["tropical","humid_subtropical"],possible:["highland"]}},
{id:204,common:"Adenium (Desert Rose)",latin:"Adenium obesum",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Adenium_obesum_2.jpg/400px-Adenium_obesum_2.jpg",water:"Weekly summer, monthly winter",sun:"Full sun 6+ hours",cycle:"Perennial",cats:["outdoor","succulent","flowering"],diff:"Easy",height:"30-90cm",soil:"Sandy cactus mix",ph:"6.0-7.0",fertilizer:"Monthly summer",propagation:"Seeds or cuttings",pests:"Mealybugs, aphids",season:{best:"Summer",sow:"March-April",harvest:"N/A",bloom:"March-October"},companion:["Bougainvillea","Marigold"],tips:["Most popular balcony plant in India","Stunning flowers all season","Dormant in winter — stop watering","Swollen caudex stores water","All parts toxic — keep from children"],climate:{best:["semiarid","arid","subtropical"],good:["tropical"],possible:["humid_subtropical"]}},
{id:205,common:"String of Pearls",latin:"Senecio rowleyanus",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Senecio_rowleyanus_-_String_of_Pearls.jpg/400px-Senecio_rowleyanus_-_String_of_Pearls.jpg",water:"Every 2 weeks",sun:"Bright indirect",cycle:"Perennial",cats:["indoor","succulent"],diff:"Moderate",height:"Trailing 60-90cm",soil:"Sandy succulent mix",ph:"6.6-7.5",fertilizer:"Monthly in season",propagation:"Stem cuttings in soil",pests:"Mealybugs, root rot",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"White cinnamon-scented"},companion:["Echeveria","Haworthia"],tips:["Beautiful in hanging pots","Flowers smell like cinnamon","Toxic to pets","Very drought tolerant","Bright indirect only"],climate:{best:["semiarid","subtropical"],good:["arid"],possible:["tropical","humid_subtropical","highland"]}},
{id:206,common:"Sedum (Stonecrop)",latin:"Sedum spectabile",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Sedum_spectabile.jpg/400px-Sedum_spectabile.jpg",water:"Every 2 weeks",sun:"Full sun",cycle:"Perennial",cats:["succulent","outdoor"],diff:"Easy",height:"30-60cm",soil:"Well-draining sandy",ph:"6.0-7.0",fertilizer:"Once in spring",propagation:"Stem or leaf cuttings",pests:"Aphids, root rot",season:{best:"Year-round",sow:"Any time",harvest:"N/A",bloom:"Pink star flowers autumn"},companion:["Echeveria","Adenium"],tips:["Drought tolerant","Attracts butterflies","Cut back after flowering","Works in rock gardens","Popular for balcony containers"],climate:{best:["semiarid","arid","subtropical"],good:["highland"],possible:["tropical","humid_subtropical"]}},
{id:207,common:"Cactus (Golden Barrel)",latin:"Echinocactus grusonii",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Golden_barrel_cactus_arp.jpg/400px-Golden_barrel_cactus_arp.jpg",water:"Every 3-4 weeks summer, monthly winter",sun:"Full sun",cycle:"Perennial",cats:["succulent","outdoor"],diff:"Easy",height:"60-90cm",soil:"Sandy cactus mix",ph:"6.0-7.0",fertilizer:"Once in spring",propagation:"Offsets or seeds",pests:"Scale, root rot",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Yellow ring flowers on mature plants"},companion:["Agave","Adenium"],tips:["Very low maintenance","Never overwater","Gorgeous in terracotta","Popular ornamental cactus in India","Spines are very sharp — handle carefully"],climate:{best:["arid","semiarid"],good:["subtropical"],possible:["tropical","highland"]}},
{id:208,common:"Agave",latin:"Agave americana",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Agave_americana_2.jpg/400px-Agave_americana_2.jpg",water:"Monthly once established",sun:"Full sun",cycle:"Perennial",cats:["succulent","outdoor"],diff:"Easy",height:"1-2m",soil:"Sandy well-draining",ph:"6.0-8.0",fertilizer:"Once in spring",propagation:"Pups at base",pests:"Agave snout weevil",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Tall flower stalk once then dies"},companion:["Cactus","Adenium"],tips:["Extremely drought tolerant","Dies after blooming — pups continue","Sap irritates skin","Very architectural plant","Perfect for dry Indian gardens"]},
// ──────── 🌸 FLOWERING ────────
{id:301,common:"Hibiscus (Gudhal)",latin:"Hibiscus rosa-sinensis",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Hibiscus_rosa-sinensis1.jpg/400px-Hibiscus_rosa-sinensis1.jpg",water:"Daily summer, every 2 days otherwise",sun:"Full sun 6+ hours",cycle:"Perennial",cats:["outdoor","flowering"],diff:"Easy",height:"1-3m",soil:"Rich well-draining loamy",ph:"6.0-7.0",fertilizer:"Weekly during blooming",propagation:"Stem cuttings in monsoon",pests:"Aphids, whiteflies, mealybugs",season:{best:"Year-round",sow:"Any time",harvest:"Flowers daily",bloom:"Year-round peak Feb-Nov"},companion:["Marigold","Jasmine"],tips:["Sacred flower for Durga and Ganesha","Used in hair oil","Hibiscus tea is healthy","Prune after flush for more blooms","Each flower lasts one day"],climate:{best:["arid","semiarid"],good:["subtropical"],possible:["tropical","highland"]}},
{id:302,common:"Marigold (Genda)",latin:"Tagetes erecta",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Tagetes_erecta_flower.jpg/400px-Tagetes_erecta_flower.jpg",water:"Every 2 days",sun:"Full sun",cycle:"Annual",cats:["outdoor","flowering"],diff:"Easy",height:"30-90cm",soil:"Any well-draining",ph:"5.8-7.0",fertilizer:"Every 2 weeks",propagation:"Seed in 5-7 days",pests:"Spider mites, powdery mildew",season:{best:"October-March",sow:"September-October",harvest:"Flowers for festivals",bloom:"November-March"},companion:["Tomato","Chilli"],tips:["Essential for every Indian festival","Natural pest repellent","Sow in October for Diwali","Deadhead for continuous flowers","Perfect first plant for children"],climate:{best:["subtropical","semiarid","humid_subtropical"],good:["tropical","arid"],possible:["highland"]}},
{id:303,common:"Jasmine (Mogra)",latin:"Jasminum sambac",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Jasminum_sambac_%28L.%29_Aiton_%28Arabian_Jasmine%29_in_Hyderabad%2C_AP_W_IMG_9978.jpg/400px-Jasminum_sambac_%28L.%29_Aiton_%28Arabian_Jasmine%29_in_Hyderabad%2C_AP_W_IMG_9978.jpg",water:"Twice weekly",sun:"Full sun to partial shade",cycle:"Perennial",cats:["outdoor","flowering"],diff:"Easy",height:"1-3m climbing",soil:"Rich well-draining",ph:"6.0-7.0",fertilizer:"Monthly in season",propagation:"Cuttings in monsoon",pests:"Aphids, mites",season:{best:"Summer and monsoon",sow:"March-April",harvest:"Flowers for garlands",bloom:"March-October"},companion:["Rose","Hibiscus"],tips:["Most fragrant Indian flower","South Indian hair garlands","Blooms most in summer heat","Early morning harvest best","Sacred across South Asia"],climate:{best:["tropical","humid_subtropical","subtropical"],good:["semiarid"],possible:["arid","highland"]}},
{id:304,common:"Rose (Gulab)",latin:"Rosa hybrida",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Red_rose.jpg/400px-Red_rose.jpg",water:"Twice weekly at base",sun:"Full sun 6+ hours",cycle:"Perennial",cats:["outdoor","flowering"],diff:"Moderate",height:"60cm-2m",soil:"Rich loamy with compost",ph:"6.0-6.5",fertilizer:"Every 2 weeks Feb-Oct",propagation:"Cuttings October-November",pests:"Black spot, aphids, powdery mildew",season:{best:"October-April",sow:"Oct-Nov",harvest:"Flowers year-round",bloom:"Nov-May and Sep-Oct"},companion:["Marigold","Lavender"],tips:["Plant in October-November","Spray neem oil for black spot","Prune hard in October","Rose water in Indian cooking","Most popular gift flower in India"],climate:{best:["subtropical","semiarid","highland"],good:["humid_subtropical"],possible:["tropical","arid"]}},
{id:305,common:"Bougainvillea",latin:"Bougainvillea spectabilis",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Bougainvillea_01.jpg/400px-Bougainvillea_01.jpg",water:"Weekly once established",sun:"Full sun 5+ hours",cycle:"Perennial",cats:["outdoor","flowering","tropical"],diff:"Easy",height:"3-10m climbing",soil:"Well-draining sandy loam",ph:"5.5-6.5",fertilizer:"Monthly phosphorus-rich",propagation:"Hardwood cuttings monsoon",pests:"Aphids, mealybugs",season:{best:"Winter-Spring",sow:"Any time",harvest:"N/A",bloom:"Nov-April peak"},companion:["Hibiscus","Plumeria"],tips:["Most dramatic Indian climber","Thrives in heat","Prune hard after flush","Colourful parts are bracts","Thorny — wear gloves"],climate:{best:["tropical","semiarid","arid","subtropical"],good:["humid_subtropical"],possible:["highland"]}},
{id:306,common:"Plumeria (Champa)",latin:"Plumeria rubra",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Plumeria_rubra1.jpg/400px-Plumeria_rubra1.jpg",water:"Weekly summer, monthly winter",sun:"Full sun",cycle:"Perennial",cats:["outdoor","flowering","tropical"],diff:"Easy",height:"2-5m",soil:"Well-draining sandy loam",ph:"6.0-7.0",fertilizer:"Monthly in season",propagation:"Branch cuttings — dry 2 weeks",pests:"Rust fungus, whiteflies",season:{best:"Summer",sow:"March-April",harvest:"Flowers for puja",bloom:"March-November"},companion:["Bougainvillea","Hibiscus"],tips:["Sacred temple flower across India","Dormant in winter — normal","Very drought tolerant","Fragrance strongest morning","Contains latex — use gloves"],climate:{best:["tropical","semiarid","subtropical"],good:["arid","humid_subtropical"],possible:["highland"]}},
{id:307,common:"Lotus (National Flower)",latin:"Nelumbo nucifera",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Lotus_flower_%28Nelumbo_nucifera%29.jpg/400px-Lotus_flower_%28Nelumbo_nucifera%29.jpg",water:"Aquatic plant",sun:"Full sun 6+ hours",cycle:"Perennial",cats:["flowering","outdoor"],diff:"Moderate",height:"60-90cm stems",soil:"Clay loam in water",ph:"6.5-8.0",fertilizer:"Aquatic tablets monthly",propagation:"Rhizomes in spring",pests:"Aphids, leaf miner",season:{best:"Summer",sow:"Feb-March rhizomes",harvest:"Seeds for makhana",bloom:"June-September"},companion:["Water Hyacinth"],tips:["National flower of India","Grows in mud but flowers pure","Full sun and warm water","Lotus seeds are popular snack","Roots used in Kashmiri cooking"],climate:{best:["tropical","humid_subtropical","subtropical"],good:["semiarid"],possible:["arid"]}},
{id:308,common:"Orchid",latin:"Phalaenopsis amabilis",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/White_orchid.jpg/400px-White_orchid.jpg",water:"Weekly — water roots directly",sun:"Bright indirect only",cycle:"Perennial",cats:["indoor","flowering"],diff:"Moderate",height:"30-60cm",soil:"Orchid bark — never soil",ph:"5.5-6.5",fertilizer:"Weekly diluted orchid fertilizer",propagation:"Keikis from flower spike",pests:"Root rot, scale",season:{best:"Year-round",sow:"N/A",harvest:"N/A",bloom:"Lasts 2-3 months"},companion:["Peace Lily","Calathea"],tips:["Roots green when watered","Never sit in water","Cool nights trigger reblooming","Aerial roots are normal","Most popular gift plant in India"],climate:{best:["tropical","humid_subtropical"],good:["subtropical","highland"],possible:["semiarid"]}},
{id:309,common:"Chrysanthemum (Guldaudi)",latin:"Chrysanthemum morifolium",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Chrysanthemum_-_floriade_canberra.jpg/400px-Chrysanthemum_-_floriade_canberra.jpg",water:"Every 2 days",sun:"Full sun",cycle:"Perennial",cats:["outdoor","flowering"],diff:"Easy",height:"30-90cm",soil:"Rich well-draining",ph:"6.0-6.5",fertilizer:"Every 2 weeks in season",propagation:"Division or cuttings",pests:"Aphids, leaf miners",season:{best:"October-January",sow:"August-September",harvest:"Cut flowers",bloom:"October-January"},companion:["Marigold","Dahlia"],tips:["Quintessential Diwali plant","Pinch tips in August","Hundreds of varieties","Popular cut flower","Withstands North Indian winters"],climate:{best:["subtropical","semiarid","humid_subtropical"],good:["highland"],possible:["tropical","arid"]}},
{id:310,common:"Dahlia",latin:"Dahlia pinnata",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Dahlia_x_hybrida.jpg/400px-Dahlia_x_hybrida.jpg",water:"Every 2 days",sun:"Full sun",cycle:"Annual",cats:["outdoor","flowering"],diff:"Moderate",height:"30cm-1.2m",soil:"Rich well-draining with compost",ph:"6.5-7.0",fertilizer:"Every 2 weeks low N high K",propagation:"Tubers October or cuttings",pests:"Aphids, earwigs, slugs",season:{best:"October-January",sow:"October",harvest:"Cut flowers",bloom:"December-February"},companion:["Marigold","Zinnia"],tips:["Plant tubers in October","Stake tall varieties","Deadhead for continuous blooms","Dig tubers in March","Over 50000 varieties worldwide"],climate:{best:["subtropical","semiarid","highland"],good:["humid_subtropical"],possible:["tropical","arid"]}},
{id:311,common:"Periwinkle (Sadabahar)",latin:"Catharanthus roseus",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Catharanthus_roseus_-_02.jpg/400px-Catharanthus_roseus_-_02.jpg",water:"Every 2 days",sun:"Full sun to partial shade",cycle:"Annual",cats:["outdoor","flowering","medicinal"],diff:"Easy",height:"30-60cm",soil:"Any well-draining",ph:"5.5-6.0",fertilizer:"Monthly",propagation:"Seeds or cuttings",pests:"Very few",season:{best:"Year-round",sow:"Any time",harvest:"N/A",bloom:"365 days a year"},companion:["Marigold","Hibiscus"],tips:["Means always blooming in Hindi","Extremely heat tolerant","Used in cancer treatment research","Good for diabetes in Ayurveda","Pink white and red varieties"],climate:{best:["tropical","subtropical","semiarid","humid_subtropical"],good:["arid"],possible:["highland"]}},
{id:312,common:"Zinnia",latin:"Zinnia elegans",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zinnia_elegans1.jpg/400px-Zinnia_elegans1.jpg",water:"Every 2 days",sun:"Full sun",cycle:"Annual",cats:["outdoor","flowering"],diff:"Easy",height:"30-90cm",soil:"Well-draining fertile",ph:"5.5-7.5",fertilizer:"Every 2 weeks",propagation:"Seeds in 7 days",pests:"Powdery mildew, spider mites",season:{best:"October-March",sow:"October-November",harvest:"Cut flowers",bloom:"December-March"},companion:["Marigold","Sunflower"],tips:["Blooms in 6 weeks from seed","Attracts butterflies","Sow October for winter colour","Deadhead for non-stop blooms","Best cut when half-open"],climate:{best:["subtropical","semiarid","humid_subtropical"],good:["tropical"],possible:["arid","highland"]}},
{id:313,common:"Sunflower (Surajmukhi)",latin:"Helianthus annuus",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Sunflower_sky_backdrop.jpg/400px-Sunflower_sky_backdrop.jpg",water:"Every 2-3 days",sun:"Full sun",cycle:"Annual",cats:["outdoor","flowering","edible"],diff:"Easy",height:"60cm-3m",soil:"Well-draining fertile",ph:"6.0-7.5",fertilizer:"Phosphate when budding",propagation:"Direct seed sowing",pests:"Aphids, birds",season:{best:"October-March",sow:"October-November",harvest:"Seeds when head dries",bloom:"December-February"},companion:["Tomato","Marigold"],tips:["Young plants track the sun","Roasted seeds popular snack","Sow October for winter blooms","Allow head to dry for seeds","Can reach 3m in Indian summer"],climate:{best:["subtropical","semiarid","humid_subtropical"],good:["tropical","arid"],possible:["highland"]}},
{id:314,common:"Crossandra (Aboli)",latin:"Crossandra infundibuliformis",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Crossandra_infundibuliformis.jpg/400px-Crossandra_infundibuliformis.jpg",water:"Every 2 days",sun:"Partial to full sun",cycle:"Perennial",cats:["outdoor","flowering"],diff:"Easy",height:"30-60cm",soil:"Well-draining loamy",ph:"6.0-7.0",fertilizer:"Monthly",propagation:"Seeds or cuttings",pests:"Aphids, whiteflies",season:{best:"Year-round South India",sow:"Any time",harvest:"Flowers for garlands",bloom:"Year-round"},companion:["Jasmine","Ixora"],tips:["Popular South Indian temple plant","Used for Tamil Nadu garlands","Blooms continuously","Loves South Indian climate","Orange flowers brighten garden"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid"]}},
{id:315,common:"Ixora (Jungle Flame)",latin:"Ixora coccinea",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Ixora_coccinea_-_scarlet_jungle_flame.jpg/400px-Ixora_coccinea_-_scarlet_jungle_flame.jpg",water:"Twice weekly",sun:"Full sun",cycle:"Perennial",cats:["outdoor","flowering"],diff:"Easy",height:"1-2m",soil:"Acidic well-draining",ph:"5.0-6.0",fertilizer:"Monthly acid fertilizer",propagation:"Stem cuttings",pests:"Aphids, scale",season:{best:"Year-round",sow:"Any time",harvest:"Flowers for offerings",bloom:"Year-round tropical"},companion:["Bougainvillea","Hibiscus"],tips:["Most popular hedge in tropical India","Offered to Shiva and Lakshmi","Needs acidic soil","Attracts butterflies","Red clusters iconic in Indian gardens"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid"]}},
{id:316,common:"Parijat (Night Jasmine)",latin:"Nyctanthes arbor-tristis",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Nyctanthes_arbor-tristis_flowers.jpg/400px-Nyctanthes_arbor-tristis_flowers.jpg",water:"Twice weekly",sun:"Full sun",cycle:"Perennial",cats:["outdoor","flowering","medicinal"],diff:"Easy",height:"4-10m",soil:"Well-draining loamy",ph:"7.0-8.0",fertilizer:"Monthly compost",propagation:"Seeds or cuttings",pests:"Very few",season:{best:"Monsoon-winter",sow:"July-August",harvest:"Flowers for puja",bloom:"August-December nights"},companion:["Tulsi","Ashoka Tree"],tips:["Sacred to Lord Vishnu","Blooms at night falls by morning","Fragrance fills garden at night","Orange stalk natural dye","Most spiritually significant flowering tree"],climate:{best:["tropical","humid_subtropical","subtropical"],good:["semiarid"],possible:["arid"]}},
{id:317,common:"Portulaca (Table Rose)",latin:"Portulaca grandiflora",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Portulaca_grandiflora_11.jpg/400px-Portulaca_grandiflora_11.jpg",water:"Every 3 days",sun:"Full sun",cycle:"Annual",cats:["outdoor","flowering"],diff:"Easy",height:"15-30cm",soil:"Sandy poor soil",ph:"5.5-7.0",fertilizer:"Rarely needed",propagation:"Seeds or cuttings",pests:"Aphids, slugs",season:{best:"Year-round warm India",sow:"Any time",harvest:"N/A",bloom:"Year-round"},companion:["Marigold","Zinnia"],tips:["Perfect for hot dry Indian summers","Flowers close at night","Thrives in poor sandy soil","Available in many hot colours","Fills bare ground beautifully"],climate:{best:["arid","semiarid","subtropical","tropical"],good:["humid_subtropical"],possible:["highland"]}},
{id:318,common:"Balsam (Gul Mehndi)",latin:"Impatiens balsamina",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Impatiens_balsamina2.jpg/400px-Impatiens_balsamina2.jpg",water:"Every 2 days",sun:"Partial shade to full sun",cycle:"Annual",cats:["outdoor","flowering"],diff:"Easy",height:"20-75cm",soil:"Rich well-draining moist",ph:"6.0-7.0",fertilizer:"Monthly",propagation:"Seeds in 7 days",pests:"Aphids, spider mites",season:{best:"Monsoon",sow:"June-July",harvest:"Seeds",bloom:"July-September"},companion:["Marigold","Petunia"],tips:["Most popular monsoon flower","Seeds eject explosively","Used in mehendi preparation","Grows in shaded spots","Perfect for rainy season balconies"]},
// ──────── 🥬 EDIBLE ────────
{id:401,common:"Tulsi (Holy Basil)",latin:"Ocimum tenuiflorum",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Ocimum_tenuiflorum_003.jpg/400px-Ocimum_tenuiflorum_003.jpg",water:"Daily",sun:"Full sun 6+ hours",cycle:"Perennial",cats:["edible","medicinal","outdoor"],diff:"Easy",height:"30-60cm",soil:"Well-draining fertile",ph:"6.0-7.5",fertilizer:"Monthly organic",propagation:"Seeds or cuttings",pests:"Few — naturally repelling",season:{best:"Year-round",sow:"Feb-March or monsoon",harvest:"Leaves year-round",bloom:"Year-round"},companion:["Tomato","Chilli"],tips:["Most sacred plant in Hinduism","Every Hindu home has Tulsi Vrindavan","Kadha tea for immunity","Natural mosquito repellent","Ram Shyam and Vana Tulsi — three varieties"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:402,common:"Mint (Pudina)",latin:"Mentha spicata",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Mint-leaves-2007.jpg/400px-Mint-leaves-2007.jpg",water:"Every 2 days",sun:"Partial shade to full sun",cycle:"Perennial",cats:["edible","medicinal","outdoor"],diff:"Easy",height:"30-90cm",soil:"Rich moist",ph:"6.0-7.0",fertilizer:"Monthly",propagation:"Runners or cuttings in water",pests:"Aphids, flea beetles",season:{best:"Winter-Spring North, year-round South",sow:"October-November",harvest:"Year-round",bloom:"Summer"},companion:["Tomato","Chilli"],tips:["Essential for chutneys and raita","Plant in containers — spreads","Harvest to prevent flowering","Fresh tea soothes digestion","Dozens of varieties all easy"],climate:{best:["subtropical","humid_subtropical","highland"],good:["tropical","semiarid"],possible:["arid"]}},
{id:403,common:"Coriander (Dhaniya)",latin:"Coriandrum sativum",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Coriander.jpg/400px-Coriander.jpg",water:"Every 2 days",sun:"Full sun to partial shade",cycle:"Annual",cats:["edible","outdoor"],diff:"Easy",height:"30-50cm",soil:"Light well-draining",ph:"6.0-7.0",fertilizer:"Light nitrogen monthly",propagation:"Direct seed only — does not transplant",pests:"Aphids, whiteflies",season:{best:"October-February",sow:"October-November",harvest:"Leaves 3-4 weeks, seeds 3 months",bloom:"Winter"},companion:["Tomato","Spinach"],tips:["Sow directly — never transplant","Crush seeds before sowing","Harvest outer leaves first","Cool season only North India","Both leaves and seeds essential in Indian cooking"],climate:{best:["subtropical","semiarid","humid_subtropical"],good:["highland"],possible:["tropical","arid"]}},
{id:404,common:"Curry Leaf (Kadipatta)",latin:"Murraya koenigii",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Curry_leaf_plant.jpg/400px-Curry_leaf_plant.jpg",water:"Twice weekly",sun:"Full sun",cycle:"Perennial",cats:["edible","medicinal","outdoor"],diff:"Easy",height:"1-4m",soil:"Well-draining loamy fertile",ph:"6.0-7.0",fertilizer:"Monthly organic",propagation:"Seeds or suckers",pests:"Scale, citrus psyllid",season:{best:"Year-round",sow:"Monsoon",harvest:"Leaves year-round",bloom:"White flowers summer"},companion:["Tulsi","Tomato"],tips:["Irreplaceable in South Indian cooking","Grows in pots on balconies","Pinch flowers for more leaves","Fresh is best — freeze extras","Leaves in hair oil reduce greying"],climate:{best:["tropical","humid_subtropical","subtropical"],good:["semiarid"],possible:["arid","highland"]}},
{id:405,common:"Chilli (Mirchi)",latin:"Capsicum annuum",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Chili_pepper_with_dew.jpg/400px-Chili_pepper_with_dew.jpg",water:"Every 2 days",sun:"Full sun",cycle:"Annual",cats:["edible","outdoor"],diff:"Easy",height:"60cm-1m",soil:"Well-draining fertile",ph:"6.0-7.0",fertilizer:"Every 2 weeks when fruiting",propagation:"Seeds — sow January",pests:"Aphids, whiteflies, fruit borers",season:{best:"Year-round India",sow:"January-February",harvest:"June-December",bloom:"April-May"},companion:["Tomato","Tulsi"],tips:["Grows on balconies in pots","Dozens of varieties","Rich in Vitamin C","Harvest when colour changes","Marigold companion reduces aphids"],climate:{best:["tropical","subtropical","semiarid","humid_subtropical"],good:["arid"],possible:["highland"]}},
{id:406,common:"Tomato (Tamatar)",latin:"Solanum lycopersicum",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/400px-Tomato_je.jpg",water:"Daily summer, every 2 days winter",sun:"Full sun 6-8 hours",cycle:"Annual",cats:["edible","outdoor"],diff:"Easy",height:"60cm-2m",soil:"Rich well-draining with compost",ph:"6.0-6.8",fertilizer:"Every 2 weeks high K when fruiting",propagation:"Seeds October-November",pests:"Fruit borer, whitefly, blight",season:{best:"October-March",sow:"October-November",harvest:"January-March",bloom:"December-January"},companion:["Basil","Marigold"],tips:["Best grown October-February","Needs staking","Feed compost weekly","Cherry tomatoes great in pots","Pinch suckers for larger fruits"],climate:{best:["subtropical","semiarid","humid_subtropical"],good:["tropical","highland"],possible:["arid"]}},
{id:407,common:"Ginger (Adrak)",latin:"Zingiber officinale",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Zingiber_officinale_root.jpg/400px-Zingiber_officinale_root.jpg",water:"Every 2 days",sun:"Partial shade",cycle:"Perennial",cats:["edible","medicinal","outdoor"],diff:"Moderate",height:"60cm-1m",soil:"Rich well-drained loamy",ph:"5.5-6.5",fertilizer:"Monthly compost",propagation:"Rhizome pieces in April",pests:"Soft rot, nematodes",season:{best:"Monsoon",sow:"April-May",harvest:"October-December",bloom:"Rarely"},companion:["Turmeric","Tulsi"],tips:["Plant before monsoon in April","Harvest when leaves yellow","Used in chai, curries, kadha","Both young and mature edible","Store in damp sand"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:408,common:"Turmeric (Haldi)",latin:"Curcuma longa",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/TurmericRoots.jpg/400px-TurmericRoots.jpg",water:"Every 2 days in season",sun:"Partial shade",cycle:"Perennial",cats:["edible","medicinal","outdoor"],diff:"Easy",height:"60cm-1m",soil:"Rich loamy well-draining",ph:"5.5-7.0",fertilizer:"Monthly organic",propagation:"Rhizomes April-May",pests:"Leaf blotch, rhizome rot",season:{best:"Monsoon",sow:"April-May",harvest:"November-January",bloom:"Yellow-white summer"},companion:["Ginger","Coriander"],tips:["Most important spice in India","Plant before monsoon","Haldi milk — ancient immune remedy","Curcumin is anti-inflammatory","Fresh root replaces dried powder"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid","highland"]}},
{id:409,common:"Fenugreek (Methi)",latin:"Trigonella foenum-graecum",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Trigonella_foenum-graecum_MS_4544.jpg/400px-Trigonella_foenum-graecum_MS_4544.jpg",water:"Every 2 days",sun:"Full sun",cycle:"Annual",cats:["edible","medicinal","outdoor"],diff:"Easy",height:"30-60cm",soil:"Well-draining fertile",ph:"6.0-7.0",fertilizer:"Light nitrogen once",propagation:"Direct sowing in 3-5 days",pests:"Very few",season:{best:"October-February",sow:"October-November",harvest:"Leaves 2-3 weeks",bloom:"Winter"},companion:["Spinach","Coriander"],tips:["Harvest leaves in 3 weeks","Both leaves and seeds in Indian cooking","Controls blood sugar","Soak seeds overnight","Microgreens ready in 7 days"],climate:{best:["subtropical","semiarid","humid_subtropical"],good:["arid","highland"],possible:["tropical"]}},
{id:410,common:"Spinach (Palak)",latin:"Spinacia oleracea",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Savoy_Cabbage_DSW.jpg/400px-Savoy_Cabbage_DSW.jpg",water:"Every 2 days",sun:"Partial shade to full sun",cycle:"Annual",cats:["edible","outdoor"],diff:"Easy",height:"15-30cm",soil:"Rich moisture-retaining",ph:"6.5-7.5",fertilizer:"Nitrogen-rich monthly",propagation:"Direct seed sowing",pests:"Leaf miners, slugs",season:{best:"October-February",sow:"October-November",harvest:"3-4 weeks after sowing",bloom:"Winter bolting"},companion:["Coriander","Methi"],tips:["Best sown in October","Harvest outer leaves first","Bolts in heat","Rich in iron for Indian vegetarian diet","Baby leaves ready in 3 weeks"],climate:{best:["subtropical","semiarid","highland"],good:["humid_subtropical"],possible:["tropical","arid"]}},
{id:411,common:"Okra (Bhindi)",latin:"Abelmoschus esculentus",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Okra_2006_Manga_04.jpg/400px-Okra_2006_Manga_04.jpg",water:"Every 2 days",sun:"Full sun",cycle:"Annual",cats:["edible","outdoor"],diff:"Easy",height:"1-2m",soil:"Well-draining fertile",ph:"6.0-6.8",fertilizer:"Monthly",propagation:"Direct seed sowing",pests:"Aphids, fruit borers",season:{best:"Summer and monsoon",sow:"Feb-March or July",harvest:"Every 2 days from June",bloom:"Yellow hibiscus flowers"},companion:["Chilli","Tomato"],tips:["Most popular summer vegetable","Harvest every 2 days or woody","Soak seeds overnight","Thrives in Indian heat","Flowers are beautiful — hibiscus family"],climate:{best:["tropical","subtropical","semiarid","humid_subtropical"],good:["arid"],possible:["highland"]}},
{id:412,common:"Garlic (Lahsun)",latin:"Allium sativum",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Garlic_bulb-1500x998.jpg/400px-Garlic_bulb-1500x998.jpg",water:"Every 3 days",sun:"Full sun",cycle:"Annual",cats:["edible","medicinal","outdoor"],diff:"Easy",height:"30-60cm",soil:"Well-draining fertile",ph:"6.0-7.0",fertilizer:"Nitrogen growing, phosphate near harvest",propagation:"Individual cloves October",pests:"Bulb rot, thrips",season:{best:"October-March",sow:"October-November",harvest:"March-April",bloom:"White globe flowers"},companion:["Rose","Tomato"],tips:["Plant cloves point-up in October","Harvest when tops brown","Natural antibiotic in Ayurveda","Braid dried for storage","Repels aphids from roses"],climate:{best:["subtropical","semiarid","highland"],good:["humid_subtropical"],possible:["tropical","arid"]}},
{id:413,common:"Bitter Gourd (Karela)",latin:"Momordica charantia",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Bitter_melon_2007.jpg/400px-Bitter_melon_2007.jpg",water:"Daily",sun:"Full sun",cycle:"Annual",cats:["edible","medicinal","outdoor"],diff:"Easy",height:"Vine 3-5m",soil:"Rich well-draining fertile",ph:"6.0-6.7",fertilizer:"Every 2 weeks",propagation:"Direct seed soak overnight",pests:"Aphids, red pumpkin beetle",season:{best:"Summer and monsoon",sow:"February-March",harvest:"June-August",bloom:"Yellow June"},companion:["Bottle Gourd","Marigold"],tips:["Train on trellis","Controls blood sugar","Bitter but highly beneficial","Hand pollinate for better yield","Popular in South Indian sambar"],climate:{best:["tropical","subtropical","humid_subtropical"],good:["semiarid"],possible:["arid","highland"]}},
{id:414,common:"Bottle Gourd (Lauki)",latin:"Lagenaria siceraria",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Lagenaria_siceraria.JPG/400px-Lagenaria_siceraria.JPG",water:"Daily",sun:"Full sun",cycle:"Annual",cats:["edible","outdoor"],diff:"Easy",height:"Vine 3-5m",soil:"Rich well-draining fertile",ph:"6.0-7.0",fertilizer:"Every 2 weeks",propagation:"Direct seed sowing",pests:"Aphids, pumpkin beetle",season:{best:"Summer and monsoon",sow:"February-March",harvest:"June-August",bloom:"White June"},companion:["Bitter Gourd","Marigold"],tips:["Most grown home vegetable in India","Train on trellis","Hand pollinate for fruit set","Harvest young for best taste","Lauki juice for weight management"],climate:{best:["tropical","subtropical","semiarid","humid_subtropical"],good:["arid"],possible:["highland"]}},
{id:415,common:"Paan (Betel Leaf)",latin:"Piper betle",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/PiperBetle.jpg/400px-PiperBetle.jpg",water:"Daily",sun:"Partial to full shade",cycle:"Perennial",cats:["edible","medicinal","outdoor"],diff:"Moderate",height:"Climber 5m",soil:"Rich moist loamy",ph:"6.0-7.5",fertilizer:"Monthly compost",propagation:"Stem cuttings",pests:"Scale, root rot",season:{best:"Monsoon",sow:"Monsoon",harvest:"Leaves year-round",bloom:"Insignificant"},companion:["Areca Palm","Neem"],tips:["Sacred in Hindu rituals","Digestive aid after meals","Grows in shade under palms","Popular in Bengal and Odisha","Loves monsoon humidity"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid"]}},
{id:416,common:"Brinjal (Baingan)",latin:"Solanum melongena",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Solanum_melongena.jpg/400px-Solanum_melongena.jpg",water:"Every 2 days",sun:"Full sun",cycle:"Annual",cats:["edible","outdoor"],diff:"Easy",height:"60cm-1m",soil:"Well-draining fertile",ph:"5.5-6.8",fertilizer:"Every 2 weeks",propagation:"Seeds sow October",pests:"Fruit borer, aphids",season:{best:"Year-round India",sow:"October-November or March",harvest:"Continuous",bloom:"Purple flowers"},companion:["Marigold","Chilli"],tips:["Grows beautifully in pots","Many varieties — round long purple white","Bharta and sabzi — endless recipes","Plant after monsoon for best results","Very popular kitchen garden plant"],climate:{best:["tropical","subtropical","semiarid","humid_subtropical"],good:["arid"],possible:["highland"]}},
{id:417,common:"Lady's Finger (Bhindi) Dwarf",latin:"Abelmoschus esculentus var. dwarf",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Okra_2006_Manga_04.jpg/400px-Okra_2006_Manga_04.jpg",water:"Every 2 days",sun:"Full sun",cycle:"Annual",cats:["edible","outdoor"],diff:"Easy",height:"60-90cm",soil:"Well-draining fertile",ph:"6.0-6.8",fertilizer:"Monthly",propagation:"Direct seed sowing",pests:"Aphids, fruit borers",season:{best:"Summer",sow:"February-March",harvest:"June onwards",bloom:"Yellow flowers"},companion:["Chilli","Tomato"],tips:["Dwarf variety perfect for pots","Harvest every 2 days","Soak seeds overnight","Thrives in Indian summer","Hibiscus family — beautiful flowers"]},
// ──────── 🌿 MEDICINAL ────────
{id:501,common:"Neem",latin:"Azadirachta indica",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Azadirachta_indica_003.jpg/400px-Azadirachta_indica_003.jpg",water:"Weekly young, drought tolerant mature",sun:"Full sun",cycle:"Perennial",cats:["medicinal","outdoor"],diff:"Easy",height:"15-20m",soil:"Any well-draining",ph:"6.2-7.0",fertilizer:"Rarely needed",propagation:"Seeds or cuttings",pests:"Almost none",season:{best:"Year-round",sow:"Monsoon",harvest:"Leaves seeds bark year-round",bloom:"White spring flowers"},companion:["Tulsi","Curry Leaf"],tips:["Village pharmacy — every part medicinal","Best organic pesticide","Datun natural toothbrush","Leaves in grain prevent insects","Seeds yield neem oil"],climate:{best:["tropical","subtropical","semiarid","humid_subtropical"],good:["arid"],possible:["highland"]}},
{id:502,common:"Ashwagandha",latin:"Withania somnifera",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Withania_somnifera_fruit.jpg/400px-Withania_somnifera_fruit.jpg",water:"Weekly — drought tolerant",sun:"Full sun",cycle:"Perennial",cats:["medicinal","outdoor"],diff:"Moderate",height:"30-75cm",soil:"Sandy well-draining",ph:"7.5-8.0",fertilizer:"Monthly organic",propagation:"Seeds sow monsoon",pests:"Root rot if overwatered",season:{best:"Monsoon-winter",sow:"June-July",harvest:"Roots January-February",bloom:"Small green-yellow"},companion:["Brahmi","Tulsi"],tips:["Most important Ayurvedic adaptogen","Roots are medicinal — harvest 6-7 months","Best in sandy Rajasthan soils","Widely available as churna","Science confirms anti-stress benefits"],climate:{best:["semiarid","arid","subtropical"],good:["tropical"],possible:["humid_subtropical","highland"]}},
{id:503,common:"Brahmi",latin:"Bacopa monnieri",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Bacopa_monnieri.jpg/400px-Bacopa_monnieri.jpg",water:"Daily — can grow in water",sun:"Partial shade to full sun",cycle:"Perennial",cats:["medicinal","outdoor"],diff:"Easy",height:"Creeping 30cm",soil:"Wet muddy or semi-aquatic",ph:"6.0-8.0",fertilizer:"Monthly light",propagation:"Cuttings root in water",pests:"Very few",season:{best:"Year-round warm India",sow:"Any time",harvest:"Leaves year-round",bloom:"Small white"},companion:["Giloy","Tulsi"],tips:["Ancient brain tonic 3000+ years","Can grow in water containers","Brahmi oil for hair and brain","Brahmi ghrita for memory","Raw leaves can be eaten daily"],climate:{best:["tropical","humid_subtropical","subtropical"],good:["semiarid"],possible:["highland"]}},
{id:504,common:"Giloy (Guduchi)",latin:"Tinospora cordifolia",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tinospora_cordifolia.jpg/400px-Tinospora_cordifolia.jpg",water:"Twice weekly",sun:"Partial shade",cycle:"Perennial",cats:["medicinal","outdoor"],diff:"Easy",height:"Climber 10m",soil:"Any well-draining",ph:"6.0-7.0",fertilizer:"Monthly organic",propagation:"Stem cuttings easy",pests:"Very few",season:{best:"Year-round",sow:"Any time",harvest:"Stems year-round",bloom:"Small yellow"},companion:["Neem","Tulsi"],tips:["Biggest immunity booster in Ayurveda","Surged after Covid","Most potent on neem tree","Stem juice with honey daily","Called Amrit — nectar of immortality"],climate:{best:["tropical","subtropical","humid_subtropical","semiarid"],good:["arid"],possible:["highland"]}},
{id:505,common:"Amla (Indian Gooseberry)",latin:"Phyllanthus emblica",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Emblica_officinalis_fruits.jpg/400px-Emblica_officinalis_fruits.jpg",water:"Weekly",sun:"Full sun",cycle:"Perennial",cats:["medicinal","edible","outdoor"],diff:"Easy",height:"8-18m",soil:"Well-draining loamy",ph:"5.0-8.5",fertilizer:"Monthly compost",propagation:"Seeds or grafted saplings",pests:"Bark caterpillar, scale",season:{best:"Winter fruits",sow:"Monsoon",harvest:"October-February",bloom:"March-May"},companion:["Tulsi","Neem"],tips:["Richest Vitamin C — 20x orange","Sacred — Amalaka Ekadashi","In Chyawanprash and Triphala","Amla oil most popular hair treatment","Both fresh and dried highly medicinal"],climate:{best:["tropical","subtropical","semiarid","humid_subtropical"],good:["arid"],possible:["highland"]}},
{id:506,common:"Shatavari",latin:"Asparagus racemosus",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Asparagus_racemosus.jpg/400px-Asparagus_racemosus.jpg",water:"Twice weekly",sun:"Partial to full sun",cycle:"Perennial",cats:["medicinal","outdoor"],diff:"Moderate",height:"Climber 2m",soil:"Well-draining rich",ph:"6.0-7.0",fertilizer:"Monthly organic",propagation:"Seeds or root division",pests:"Root rot, aphids",season:{best:"Monsoon",sow:"June-July",harvest:"Roots 2nd year",bloom:"White fragrant"},companion:["Ashwagandha","Brahmi"],tips:["Most important women's herb in Ayurveda","Widely available as churna","Needs support structure to climb","Roots are medicinal","Science confirms galactagogue properties"],climate:{best:["tropical","humid_subtropical","subtropical"],good:["semiarid"],possible:["highland"]}},
{id:507,common:"Mulethi (Liquorice)",latin:"Glycyrrhiza glabra",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Glycyrrhiza_glabra_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-071.jpg/400px-Glycyrrhiza_glabra_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-071.jpg",water:"Weekly",sun:"Full sun",cycle:"Perennial",cats:["medicinal","outdoor"],diff:"Moderate",height:"60cm-1m",soil:"Deep well-draining fertile",ph:"6.0-8.0",fertilizer:"Monthly organic",propagation:"Root division or seeds",pests:"Root rot, aphids",season:{best:"Year-round",sow:"Spring",harvest:"Roots after 2-3 years",bloom:"Purple-blue flowers summer"},companion:["Ashwagandha"],tips:["Roots for throat and digestive health","Takes 2-3 years to mature","Common in North Indian remedies","Used in herbal teas and churna","Anti-inflammatory properties well researched"]},
// ──────── 🌴 TROPICAL ────────
{id:601,common:"Banana (Kela)",latin:"Musa acuminata",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana-Platano.jpg/400px-Banana-Platano.jpg",water:"Daily summer",sun:"Full sun",cycle:"Perennial",cats:["tropical","edible","outdoor"],diff:"Easy",height:"2-5m",soil:"Rich deep loamy",ph:"5.5-7.0",fertilizer:"Monthly high-potassium",propagation:"Suckers at base",pests:"Panama wilt, weevil, sigatoka",season:{best:"Year-round tropical",sow:"Monsoon",harvest:"12 months after planting",bloom:"Purple banana flower"},companion:["Papaya","Moringa"],tips:["Entire plant is useful","Leaves for puja and serving food","Plant new sucker every year","Harvest when top fruits start yellowing","Main plant dies — suckers continue"],climate:{best:["semiarid","subtropical"],good:["arid","highland"],possible:["tropical","humid_subtropical"]}},
{id:602,common:"Papaya (Papita)",latin:"Carica papaya",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Papaya_ES.jpg/400px-Papaya_ES.jpg",water:"Every 2 days",sun:"Full sun",cycle:"Perennial",cats:["tropical","edible","outdoor"],diff:"Easy",height:"2-8m",soil:"Rich well-draining fertile",ph:"6.0-6.5",fertilizer:"Monthly NPK",propagation:"Seeds germinate 2 weeks",pests:"Papaya mealybug, leaf curl",season:{best:"Year-round warm India",sow:"February-March",harvest:"8-10 months",bloom:"Continuous"},companion:["Banana","Moringa"],tips:["Fruits in 9 months","Most popular kitchen garden plant","Papaya leaf for dengue","Raw papaya in sabzi and chaat","Papain enzyme aids digestion"],climate:{best:["tropical","humid_subtropical"],good:["subtropical","semiarid"],possible:["arid"]}},
{id:603,common:"Mango (Aam)",latin:"Mangifera indica",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Hapus_Mango.jpg/400px-Hapus_Mango.jpg",water:"Weekly young, biweekly mature",sun:"Full sun",cycle:"Perennial",cats:["tropical","edible","outdoor"],diff:"Moderate",height:"10-40m",soil:"Deep well-draining loamy",ph:"5.5-7.5",fertilizer:"Monthly first 3 years",propagation:"Grafted saplings for variety",pests:"Mango hopper, powdery mildew",season:{best:"Summer",sow:"Monsoon new plants",harvest:"April-June",bloom:"December-January"},companion:["Tulsi","Neem"],tips:["National fruit of India","Grafted plants fruit 3-4 years","Needs dry spell in winter to flower","Alphonso Dashehri Langra Chaunsa — hundreds of varieties","Mango leaves in all puja"],climate:{best:["tropical","subtropical","semiarid","humid_subtropical"],good:["arid"],possible:["highland"]}},
{id:604,common:"Guava (Amrood)",latin:"Psidium guajava",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Guava_ID.jpg/400px-Guava_ID.jpg",water:"Twice weekly",sun:"Full sun",cycle:"Perennial",cats:["tropical","edible","outdoor"],diff:"Easy",height:"3-10m",soil:"Any well-draining",ph:"4.5-7.5",fertilizer:"Monthly compost",propagation:"Seeds or air-layering",pests:"Fruit fly, mealy bug",season:{best:"Winter fruits",sow:"Monsoon",harvest:"October-February",bloom:"Spring"},companion:["Papaya","Banana"],tips:["Easy to grow across India","Fruits 2-3 years from grafted","4x Vitamin C of orange","Popular chaat with black salt","Leaves for diarrhoea treatment"],climate:{best:["tropical","subtropical","semiarid","humid_subtropical"],good:["arid"],possible:["highland"]}},
{id:605,common:"Moringa (Drumstick)",latin:"Moringa oleifera",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Moringa_oleifera_Blanco2.388.jpg/400px-Moringa_oleifera_Blanco2.388.jpg",water:"Weekly — drought tolerant",sun:"Full sun",cycle:"Perennial",cats:["tropical","edible","medicinal","outdoor"],diff:"Easy",height:"5-12m",soil:"Any well-draining",ph:"6.0-7.0",fertilizer:"Rarely needed",propagation:"Seeds or large branch cuttings",pests:"Very few",season:{best:"Year-round tropical India",sow:"March-April or monsoon",harvest:"Pods and leaves year-round",bloom:"White year-round"},companion:["Papaya","Banana"],tips:["Called Miracle Tree — every part edible","Leaves: 7x Vit C, 4x calcium of milk","Essential in South Indian sambhar","Moringa powder world superfood","Grows from branch cuttings easily"],climate:{best:["tropical","semiarid","subtropical","humid_subtropical"],good:["arid"],possible:["highland"]}},
{id:606,common:"Coconut (Nariyal)",latin:"Cocos nucifera",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Coconut_on_palm_tree_1.jpg/400px-Coconut_on_palm_tree_1.jpg",water:"Twice weekly",sun:"Full sun",cycle:"Perennial",cats:["tropical","edible","outdoor"],diff:"Moderate",height:"25-30m",soil:"Sandy coastal",ph:"5.0-8.0",fertilizer:"Monthly early years",propagation:"Germinated nuts",pests:"Coconut mite, rhinoceros beetle",season:{best:"Year-round coastal tropical",sow:"Monsoon",harvest:"Year-round",bloom:"Year-round"},companion:["Banana","Paan"],tips:["Kalpavriksha — tree of life","Used in every South Indian meal and puja","Takes 6-10 years to fruit","Needs coastal tropical climate","Tender coconut water — perfect electrolyte"],climate:{best:["tropical"],good:["humid_subtropical"],possible:["subtropical"]}},
{id:607,common:"Jackfruit (Kathal)",latin:"Artocarpus heterophyllus",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Jackfruit_Jonatan_Riek.jpg/400px-Jackfruit_Jonatan_Riek.jpg",water:"Weekly",sun:"Full sun",cycle:"Perennial",cats:["tropical","edible","outdoor"],diff:"Easy",height:"8-25m",soil:"Deep well-draining loamy",ph:"6.0-7.5",fertilizer:"Monthly compost",propagation:"Seeds germinate 3-8 weeks",pests:"Fruit fly, mealy bug",season:{best:"Summer",sow:"Monsoon",harvest:"April-June",bloom:"Spring"},companion:["Mango","Banana"],tips:["World's largest tree fruit — up to 35kg","Popular vegan meat substitute","3-5 years from seed to fruit","Very popular in Kerala Karnataka Bengal","Leaves used as natural plates"]},
// ──────── 🙏 SACRED ────────
{id:701,common:"Tulsi (Sacred Vrindavan)",latin:"Ocimum tenuiflorum",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Ocimum_tenuiflorum_003.jpg/400px-Ocimum_tenuiflorum_003.jpg",water:"Daily",sun:"Full sun",cycle:"Perennial",cats:["outdoor","medicinal","edible"],diff:"Easy",height:"30-60cm",soil:"Well-draining fertile",ph:"6.0-7.5",fertilizer:"Monthly",propagation:"Seeds or cuttings",pests:"Few — naturally repelling",season:{best:"Year-round",sow:"Feb-March",harvest:"Year-round",bloom:"Year-round"},companion:["Neem","Curry Leaf"],tips:["Most sacred plant in Hinduism","Every Hindu home has Tulsi Vrindavan","Tulsi Vivah ceremony in Kartik month","Never pick on Sunday or Ekadashi","Ram Shyam and Vana — three varieties"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid"]}},
{id:702,common:"Bilva (Bel Tree)",latin:"Aegle marmelos",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Aegle_marmelos_4.jpg/400px-Aegle_marmelos_4.jpg",water:"Weekly",sun:"Full sun",cycle:"Perennial",cats:["medicinal","outdoor"],diff:"Easy",height:"6-9m",soil:"Any well-draining",ph:"5.0-8.0",fertilizer:"Yearly compost",propagation:"Seeds",pests:"Very few",season:{best:"Year-round",sow:"Monsoon",harvest:"Winter fruits",bloom:"White fragrant spring"},companion:["Ashoka","Parijat"],tips:["Sacred to Shiva — trifoliate leaves = Trinity","Bilva leaves in Shiva worship daily","Bel fruit juice for IBS treatment","Drought tolerant once established","Found in ancient temples across India"],climate:{best:["subtropical","semiarid","tropical","humid_subtropical"],good:["arid"],possible:["highland"]}},
{id:703,common:"Ashoka Tree",latin:"Saraca asoca",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Saraca_asoca_flowers.jpg/400px-Saraca_asoca_flowers.jpg",water:"Twice weekly",sun:"Partial shade",cycle:"Perennial",cats:["medicinal","outdoor","flowering"],diff:"Moderate",height:"6-9m",soil:"Rich moist well-draining",ph:"6.0-7.0",fertilizer:"Monthly organic",propagation:"Seeds slow germination",pests:"Scale, root rot in waterlogging",season:{best:"Winter flowering",sow:"Monsoon",harvest:"Bark medicinal",bloom:"January-April orange-red"},companion:["Parijat","Coconut"],tips:["Sacred in Hinduism and Buddhism","Sita sat under Ashoka in Lanka","Stunning orange-red flower clusters","Bark in Ashokarishta for women","Most beautiful sacred flowering tree"],climate:{best:["tropical","humid_subtropical"],good:["subtropical"],possible:["semiarid"]}},
{id:704,common:"Parijat (Night Flowering Jasmine)",latin:"Nyctanthes arbor-tristis",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Nyctanthes_arbor-tristis_flowers.jpg/400px-Nyctanthes_arbor-tristis_flowers.jpg",water:"Twice weekly",sun:"Full sun",cycle:"Perennial",cats:["outdoor","flowering","medicinal"],diff:"Easy",height:"4-10m",soil:"Well-draining loamy",ph:"7.0-8.0",fertilizer:"Monthly compost",propagation:"Seeds or cuttings",pests:"Very few",season:{best:"Monsoon-winter",sow:"July-August",harvest:"Flowers for puja",bloom:"August-December nights"},companion:["Tulsi","Bilva"],tips:["Sacred to Lord Vishnu","Blooms at night falls by morning","Fragrance fills garden at night","Orange stalk natural dye","Used in temple offerings"]},
// ──────── 🌳 OUTDOOR ────────
{id:801,common:"Croton",latin:"Codiaeum variegatum",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Codiaeum_variegatum_cultivars.jpg/400px-Codiaeum_variegatum_cultivars.jpg",water:"Every 2 days",sun:"Full sun to bright",cycle:"Perennial",cats:["outdoor","indoor"],diff:"Easy",height:"1-2m",soil:"Rich well-draining",ph:"5.0-6.0",fertilizer:"Monthly in season",propagation:"Stem cuttings",pests:"Spider mites, scale",season:{best:"Year-round",sow:"Any time",harvest:"N/A",bloom:"Insignificant"},companion:["Hibiscus","Ixora"],tips:["Popular ornamental across India","More sun = more vibrant colour","Many varieties available","Common hedge plant","Milky sap irritates skin"],climate:{best:["tropical","humid_subtropical","subtropical"],good:["semiarid"],possible:["arid"]}},
{id:802,common:"Bamboo",latin:"Bambusoideae sp.",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Moso_bamboo_in_forest.jpg/400px-Moso_bamboo_in_forest.jpg",water:"Twice weekly",sun:"Full sun to partial shade",cycle:"Perennial",cats:["outdoor"],diff:"Easy",height:"3-20m",soil:"Rich well-draining moist",ph:"5.5-7.0",fertilizer:"Monthly nitrogen",propagation:"Division of clumps",pests:"Bamboo mite, mealybug",season:{best:"Year-round",sow:"Monsoon division",harvest:"Mature culms",bloom:"Once in lifetime"},companion:["Banana","Areca Palm"],tips:["Fastest growing plant on Earth","Use clumping varieties only","Excellent privacy screen","Shoots edible in Northeast India","Lucky bamboo is actually Dracaena"],climate:{best:["tropical","humid_subtropical","subtropical"],good:["semiarid","highland"],possible:["arid"]}},
{id:803,common:"Lavender",latin:"Lavandula angustifolia",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Garden_in_Provence%2C_France_-_lavender.jpg/400px-Garden_in_Provence%2C_France_-_lavender.jpg",water:"Every 2 weeks",sun:"Full sun",cycle:"Perennial",cats:["outdoor","flowering","medicinal"],diff:"Moderate",height:"30-90cm",soil:"Well-draining sandy loam",ph:"6.5-7.5",fertilizer:"Once in spring",propagation:"Cuttings late summer",pests:"Root rot main threat",season:{best:"October-March",sow:"October",harvest:"Flowers in bud",bloom:"March-May"},companion:["Rose","Rosemary"],tips:["Grows in Himalayan foothills","Natural mosquito repellent","Harvest before fully open","Lavender oil in aromatherapy","Needs excellent drainage"],climate:{best:["highland","semiarid"],good:["subtropical"],possible:["tropical","humid_subtropical","arid"]}},
{id:804,common:"Portulaca",latin:"Portulaca grandiflora",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Portulaca_grandiflora_11.jpg/400px-Portulaca_grandiflora_11.jpg",water:"Every 3 days",sun:"Full sun",cycle:"Annual",cats:["outdoor","flowering"],diff:"Easy",height:"15-30cm",soil:"Sandy poor soil",ph:"5.5-7.0",fertilizer:"Rarely needed",propagation:"Seeds or cuttings",pests:"Aphids, slugs",season:{best:"Year-round warm India",sow:"Any time",harvest:"N/A",bloom:"Year-round"},companion:["Marigold","Zinnia"],tips:["Perfect for hot dry Indian summers","Flowers close at night","Thrives in poor sandy soil","Available in many hot colours","Fills bare ground"],climate:{best:["arid","semiarid","subtropical","tropical"],good:["humid_subtropical"],possible:["highland"]}},
{id:805,common:"Balsam",latin:"Impatiens balsamina",img:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Impatiens_balsamina2.jpg/400px-Impatiens_balsamina2.jpg",water:"Every 2 days",sun:"Partial shade to full sun",cycle:"Annual",cats:["outdoor","flowering"],diff:"Easy",height:"20-75cm",soil:"Rich well-draining moist",ph:"6.0-7.0",fertilizer:"Monthly",propagation:"Seeds in 7 days",pests:"Aphids, spider mites",season:{best:"Monsoon",sow:"June-July",harvest:"Seeds",bloom:"July-September"},companion:["Marigold","Petunia"],tips:["Most popular monsoon flower","Seeds eject explosively — fun for children","Grows in shaded spots","Perfect for rainy season balconies","Used in mehendi preparation"]},
];


// ══════════════════════════════════════════
// ADMIN OVERRIDES — load edited plants from admin panel
// Can be re-run when localStorage changes (storage event)
// ══════════════════════════════════════════
function applyAdminPlantOverrides() {
  try {
    const s = localStorage.getItem('np_admin_plants');
    if (!s) return;
    const overrides = JSON.parse(s);
    if (!Array.isArray(overrides) || !overrides.length) return;
    overrides.forEach(edited => {
      const idx = PLANT_DB.findIndex(p => p.id === edited.id);
      if (idx > -1) PLANT_DB[idx] = edited;
      else PLANT_DB.push(edited);
    });
  } catch(e) {}
}
applyAdminPlantOverrides();
